### ISSUE TITLE
Move away from alert boxes

### ISSUE THREAD

**Issue by yushan87** [ClemsonRSRG/bydesign#3]
Other than the `End survey` button, everything else that generates some kind of message gets displayed as an alert box. It is entirely possible that the user suppresses alert boxes and cause them not being able to see the messages we want them to see. 

Minimally, we should try to use jQuery's dialog boxes. The more ideal solution would be using Bootstrap.

**Comment by timschwab** [comment]
Resolved with jQuery. If we switch to Bootstrap, this should be re-addressed.
