### ISSUE TITLE
Use the verifier to check that the students inputted what we want

### ISSUE THREAD

**Issue by timschwab** [ClemsonRSRG/bydesign#7]
When we check a student's answer, we go through these steps:

- Send the code to the VC generator and check for syntax
- Send the VCs to the verifier to confirm they are true
- Check the string to ensure that the right answer they put is the correct answer that we want

This final step is the issue; it is very simple and easily fooled. For example, if we want `x + y` and they put `x + y - 1 + 1`, then in the current system, it will come out as incorrect. To solve this, we should verify that what they put is what we want in a different way. Instead of checking the string bluntly, we should extract what they said, `x + y - 1 + 1` and put it in a confirm statement like so: `Confirm x + y = x + y - 1 + 1`. Then send this statement to the verifier. We already have a powerful verifier, so we should use it.

**Comment by yushan87** [comment]
Murali proposed an alternative solution. Changes coming soon.

**Comment by timschwab** [comment]
Instead of using the verifier, we are checking to ensure that the student does not use a variable to confirm itself. For example, the student is allowed to write `Confirm I = #I`, but not `Confirm I = I`.

**Comment by yushan87** [comment]
For now, our `Confirm` clauses cannot have logical connectives of any sort (i.e. `and`, `or`, `implies`, etc.). Might have to revisit this once we have more complex examples or have things involving lambda and/or function expressions.
